### ISSUE TITLE
Unable to write file

### ISSUE THREAD

**Issue by chaz-clark** [koolkdev/disc2app#2]
I was able to copy the first disk. I removed the folder from the SD card to free up space for the next disk. Now I am getting an 'unable to wire file' error. I select A for SD card, insert the disk, it tries writing the title file, then gives the error. Are there other files that need to be cleaned off the SD card after it's installed to USB to avoid this error?

**Comment by Masamune3210** [comment]
make sure you didn't accidentally set the write protect notch when putting the SD card in

**Comment by chaz-clark** [comment]
> make sure you didn't accidentally set the write protect notch when putting the SD card in

I guessed and deleted another folder that was new and might have been created in the process, this seemed to fix it, no more error.
