### ISSUE TITLE
Doesn't work without cfw

### ISSUE THREAD

**Issue by Gyuyu8** [koolkdev/disc2app#4]
Doesn't work without cfw I tried

**Comment by Masamune3210** [comment]
Not what they meant, they meant without tiramisu. Try running it under haxchi or mocha in other words

**Comment by Gyuyu8** [comment]
How do you do that ? Don't want to brick my wiiu

**Comment by Gyuyu8** [comment]
???

**Comment by Masamune3210** [comment]
Did you not learn anything from the last post about spamming lol
If you cant be bothered to try to find out how yourself, just use this
https://github.com/wiiu-env/wudd

**Comment by Gyuyu8** [comment]
Ignorant bastards

**Comment by koolkdev** [comment]
@Gyuyu8 has been blocked from posting on this repository.
This is an (inactive) open source project, no one is obligated to help you.
@Masamune3210 gave you an alternative solution but you are still being rude.

**Comment by DominusExult** [comment]
For what it's worth, I found that Tiramisu from early March'22 allows disc2app to run and it works (I dumped my Zelda BotW, Windwaker, Hyrule Warrior, Minecraft and they installed fine).
BUT beware, there is likely a reason that Tiramisu evolved from the version back then (and newer homebrew apps won't run correctly on older Tiramisu).
